version: '3.9'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "19000:19000"  # Metro bundler
      - "19001:19001"  # LAN
      - "19002:19002"  # Dev tools
    volumes:
      - ./frontend:/app
    command: npx expo start --tunnel
    stdin_open: true
    tty: true

  backend:
    build:
      context: ./backend
    ports:
      - "7000:7000"
    volumes:
      - ./backend:/app
    command: node server.js
